import streamlit as st
import numpy as np
import plotly.express as px

# 1. IMPORT MODULAR STRUCTURAL UTILITIES AND MULTI-AGENTS
from src.utils import inject_custom_css, format_metric
from src.agents import DataIngestionAgent, AnalyticsAgent, VisualEngineAgent, MLAgent

# ==========================================
# STREAMLIT UI PRESENTATION LAYER CONFIGURATION
# ==========================================
st.set_page_config(
    page_title="SmartCity Multi-Agent Analytics", 
    layout="wide", 
    page_icon="🏙️"
)

# Inject custom clean dashboard visual elements (cards, headers, terminal looks)
inject_custom_css()

st.title("🏙️ Smart City Surveillance Analytics & Modeling Engine")
st.markdown("An autonomous multi-agent operational workflow powered by Machine Learning for public safety assessment.")

# ==========================================
# CACHED DATA PIPELINE INITIALIZATION
# ==========================================
@st.cache_data(show_spinner="Agent Ingestion Pipeline Active...")
def run_ingestion_pipeline():
    """Triggers the Data Ingestion Agent to load and preprocess the dataset safely."""
    ingestion_agent = DataIngestionAgent('v10_Addresses_camera_installation.csv')
    return ingestion_agent.process()

# Load cleaned dataset across the app session
df_clean = run_ingestion_pipeline()

# Instantiate specialized analytical, visualization, and ML modeling agents
analytics_agent = AnalyticsAgent(df_clean)
visual_agent = VisualEngineAgent(df_clean)
ml_agent = MLAgent(df_clean)

# ==========================================
# SIDEBAR MULTI-AGENT CONTROL CONSOLE
# ==========================================
st.sidebar.title("🤖 Multi-Agent Console")
st.sidebar.markdown("<div class='agent-terminal'>STATUS: ALL AGENTS OPERATIONAL<br>FLEET COUNT: 62,578 CAMERAS</div>", unsafe_allow_html=True)

selected_tab = st.sidebar.radio(
    "Navigate Analytical Workspace:", 
    [
        "Macro Analytics Hub", 
        "Territorial Stratification (Clustering)", 
        "Asset Requirement Estimation"
    ]
)

st.sidebar.markdown("---")
st.sidebar.info(
    "ℹ️ **System Node Notice:** This workspace architecture abstracts processing concerns away from data visualization maps for optimal deployment scaling."
)

# ==========================================
# WORKSPACE NAVIGATION LOGIC
# ==========================================

# --- TAB 1: MACRO ANALYTICS HUB ---
if selected_tab == "Macro Analytics Hub":
    st.subheader("📊 Strategic Fleet Overview")
    metrics = analytics_agent.get_macro_metrics()
    
    # Render customized aesthetic UI metric KPI boards
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.markdown(
            f"<div class='metric-card'><h4>Total Managed Nodes</h4><h2>{format_metric(metrics['total_addresses'])}</h2></div>", 
            unsafe_allow_html=True
        )
    with col2:
        st.markdown(
            f"<div class='metric-card'><h4>Active Camera Fleet</h4><h2>{format_metric(metrics['total_cameras'])}</h2></div>", 
            unsafe_allow_html=True
        )
    with col3:
        st.markdown(
            f"<div class='metric-card'><h4>Mean Fleet Per Node</h4><h2>{metrics['avg_cameras']:.2f}</h2></div>", 
            unsafe_allow_html=True
        )
    with col4:
        st.markdown(
            f"<div class='metric-card'><h4>Max Deployment Peak</h4><h2>{metrics['max_cameras']}</h2></div>", 
            unsafe_allow_html=True
        )

    st.markdown("---")
    
    # Structural Layout Split for plots generated by the VisualEngineAgent
    col_chart1, col_chart2 = st.columns([3, 2])
    with col_chart1:
        st.plotly_chart(visual_agent.plot_district_distribution(), use_container_width=True)
    with col_chart2:
        st.plotly_chart(visual_agent.plot_street_type_distribution(), use_container_width=True)


# --- TAB 2: TERRITORIAL STRATIFICATION ---
elif selected_tab == "Territorial Stratification (Clustering)":
    st.subheader("🤖 Urban Structural Segmentation via Unsupervised K-Means")
    st.markdown(
        "The **ML Core Agent** has compiled macro-level district variables to group administrative sectors into distinct infrastructural tiers."
    )
    
    # Process Unsupervised Cluster Tiers
    cluster_df = ml_agent.run_district_clustering()
    
    fig_cluster = px.scatter(
        cluster_df, x='address_count', y='total_cameras', size='mean_cameras',
        color='Hub_Classification', hover_name='Район',
        title="<b>District Structural Partitioning Map</b>",
        labels={'address_count': 'Total Address Coordinates', 'total_cameras': 'Total Deployed Cameras'},
        color_discrete_sequence=px.colors.qualitative.G10
    )
    fig_cluster.update_layout(template='plotly_dark', paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig_cluster, use_container_width=True)
    
    st.write("### Detailed Tier Allocation Summary")
    
    # Format and present sorted data frame overview safely to the user view
    leaderboard_view = cluster_df[['Район', 'address_count', 'total_cameras', 'mean_cameras', 'Hub_Classification']].copy()
    leaderboard_view.columns = ['District Name', 'Total Addresses', 'Total Cameras', 'Average Cameras/Node', 'Strategic Classification Cluster']
    st.dataframe(leaderboard_view.sort_values(by='Total Cameras', ascending=False), use_container_width=True, hide_index=True)


# --- TAB 3: ASSET REQUIREMENT ESTIMATION ---
elif selected_tab == "Asset Requirement Estimation":
    st.subheader("🔮 Predictive Asset Infrastructure Capacity Modeling")
    st.markdown(
        "This component triggers a **Supervised Random Forest Regressor** to estimate security architecture scaling volumes on new or simulated urban locations."
    )
    
    # Execute Model Training & Capture Optimization Metrics
    with st.spinner("Model Agent training predictive matrix..."):
        rmse, r2 = ml_agent.train_predictive_regressor()
        
    st.success(f"Model Optimization Status: Active | Target Evaluation Metrics: RMSE = {rmse:.4f} | R² Variance Score = {r2:.4f}")
    
    st.markdown("#### Dynamic Real-Time Parameter Inference Simulator")
    input_col1, input_col2, input_col3 = st.columns(3)
    
    with input_col1:
        selected_district = st.selectbox("Select Target District (Район):", sorted(df_clean['Район'].unique()))
    with input_col2:
        selected_street = st.selectbox("Select Built Environment Category:", sorted(df_clean['Street_Type'].unique()))
    with input_col3:
        addr_text = st.text_input("Enter Mock Local Address String for Feature Parsing:", "Невский проспект, дом 100")
        
    # Trigger supervised estimation inference pipeline 
    if st.button("Execute Estimator Inference", type="primary"):
        calculated_pred = ml_agent.estimate_capacity(selected_district, selected_street, len(addr_text))
        
        # Enforce logical ceiling on counts (you can't deploy a fraction of a camera)
        final_allocation = int(np.ceil(calculated_pred))
        
        st.markdown("---")
        st.metric(
            label="🎯 Recommended Infrastructure Camera Allocation", 
            value=f"{final_allocation} Active Units",
            delta=f"Based on historical density metrics for {selected_street.split(' ')[0]}"
        )
        st.info(
            "💡 **Statistical Insight:** This calculation processes historical administrative counts alongside textual addressing lengths to forecast target infrastructure demands."
        )
